### ISSUE TITLE
#1 Application Error

### ISSUE THREAD

**Issue by Marcosreuquen** [Alvax10/desafio-final-m7#1]
Buenas, Alvax!! 

Al ingresar da **Application Error** de Heroku. 

![image](https://user-images.githubusercontent.com/75027556/148131105-ff464d42-ffb1-40ad-9d19-096d5f0083bc.png)

Si querés lo charlamos en el discord a ver por dónde va el error. 

Saludos!

**Comment by Alvax10** [comment]
Ahh disculpame marcos! ahora me fijo que pudo haber pasado, graciass!

**Comment by WASD6570** [comment]
Hola @Alvax10 sigo con el mismo problema de marcos

**Comment by Alvax10** [comment]
Buenas @WASD6570 , que raro que me volvió a pasar, ayer cuando lo subí a heroku me anduvo bien y ahora tmb me esta tirando ese error a mi

**Comment by Alvax10** [comment]
@WASD6570 ahora voy a ver que le pasó y lo vuelvo a subir, gracias por notificar!

**Comment by Marcosreuquen** [comment]
Holis, @Alvax10 
Vi que lo solucionaste, pero me tira otro problema ahora(similar);
![image](https://user-images.githubusercontent.com/75027556/149336072-3f8d14c1-dff6-4e82-ad5a-9a95820a613c.png)

Parece que pide el mail al estado antes de estar cargado:
![image](https://user-images.githubusercontent.com/75027556/149336262-cbc6747e-cfbb-4358-92d0-9539a2d4f235.png)
![image](https://user-images.githubusercontent.com/75027556/149336308-565322fc-dfc2-4d16-9f62-ac7f79af37e2.png)

O puede ser algo del back, porque se envía un pedido y tira 503:
![image](https://user-images.githubusercontent.com/75027556/149336486-d62e7a4e-595a-44c5-8fb8-1c28efe76376.png)

Cualquier cosa si necesitas ayuda en algo de esto avisame o etiquetame. 
Saludos!!

**Comment by Alvax10** [comment]
Buenas @Marcosreuquen !! Te tira ese error porque cambié la URL de la API!! estaba haciendo unos cambios finales y todavía no lo actualicé!

Me falta corregir un ultimo error y es que cuando le doy a reportar una mascota el fetch funciona muy lento y no termina de cargar, cuando solucione ese problema te aviso para que puedas cargar la página! saludoss

**Comment by Marcosreuquen** [comment]
Ahhh, oka! Bueno, cierro este issue porque el origen ya se solucionó. :+1:
